# Generated by Django 5.0.1 on 2024-04-11 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200, null=True)),
                ('sub_title1', models.CharField(max_length=200, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='')),
                ('paragraph1', models.CharField(max_length=2000, null=True)),
                ('sub_title2', models.CharField(max_length=200, null=True)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('paragraph2', models.CharField(max_length=2000, null=True)),
                ('sub_title3', models.CharField(max_length=200, null=True)),
                ('img3', models.ImageField(blank=True, null=True, upload_to='')),
                ('paragraph3', models.CharField(max_length=2000, null=True)),
                ('sub_title4', models.CharField(max_length=200, null=True)),
                ('img4', models.ImageField(blank=True, null=True, upload_to='')),
                ('paragraph4', models.CharField(max_length=2000, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
